### ISSUE TITLE
footer and header support

### ISSUE THREAD

**Issue by yildo** [mikemaccana/python-docx#79]
Hi,

Do you have any idea if python-docx will support header and footer and if so when do you expect to support this feature?

**Comment by scanny** [comment]
Hi @yildo, I think you're in the wrong repository. This one is for support of the v0.2.x versions of the `docx` package. No new development is being done on these versions. The current python-docx repository (current version v0.8.5) is over here: https://github.com/python-openxml/python-docx

There is an open issue for header and footer support there:
https://github.com/python-openxml/python-docx/issues/104

This feature is close to the top of the backlog, so should be coming soon. If you're suitably motivated and have the Python skills, there are some folks who've been able to make it work for their purposes in the links there.
