### ISSUE TITLE
Create exe file from py file with docx

### ISSUE THREAD

**Issue by mayuryeola** [mikemaccana/python-docx#82]
I use python docx to save a doc file through python 2.7 but I can not able to create the executable file.
Could you please help?
Thanks

My code is
from docx import Document

import docx
document = Document('D:/CI1.docx')
Annex_CI = document.add_paragraph()
run = Annex_CI.add_run('Report No.:')
document.save('D:/CI1.docx')

Mayur

**Comment by mikemaccana** [comment]
See `README.md`
